name: domain
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  logging: 1.1.1
  build_runner: ^2.3.3

flutter:
