name: core
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  get_it: ^7.2.0
  logger: ^1.3.0
  clipboard: ^0.1.3
  flutter_bloc: ^8.1.1
  app_settings: ^5.0.0
  wallet_connect_v2: ^1.0.7
  easy_localization: ^3.0.2
  currency_formatter: ^2.1.0
  ethereum_addresses: ^1.0.2
  permission_handler: ^10.4.3
  currency_text_input_formatter: ^2.1.10
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - resources/