name: import_address
publish_to: none

include: ../../pubspec.yaml

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  data:
    path: ../../data
  domain:
    path: ../../domain
  core_ui:
    path: ../../core_ui
  core:
    path: ../../core
  navigation:
    path: ../../navigation