name: core_ui
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  domain:
    path: ../domain
  navigation:
    path: ../navigation

flutter:
  uses-material-design: true