name: navigation
publish_to: none

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=3.0.1"

dependencies:
  auto_route: ^5.0.4
  flutter:
    sdk: flutter

  core:
    path: ../core
  core_ui:
    path: ../core_ui
  domain:
    path: ../domain
  auth:
    path: ../feature/auth
  home:
    path: ../feature/home
  import_address:
    path: ../feature/import_address
  public_strategies:
    path: ../feature/public_strategies
  my_wallet:
    path: ../feature/my_wallet
  my_strategies:
    path: ../feature/my_strategies
  info:
    path: ../feature/info
  create_address:
    path: ../feature/create_address

  uni_links: ^0.5.1

dev_dependencies:
  flutter_lints: ^3.0.1
  dart_code_metrics: ^5.7.6
  auto_route_generator: 5.0.3
  build_runner: ^2.4.5