FROM node:lts-slim
WORKDIR /app
COPY ./package.json .
COPY ./yarn.lock .
RUN yarn install --frozen-lockfile --non-interactive
COPY . .
RUN yarn build
CMD ["sh", "-c", "yarn typeorm:run-migrations && node dist/apps/degen-hack/main"]
